name: Release to Docker Hub

on:
  push:
    tags:
      - "*.*.*"

jobs:

  release:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      
      - name: Checkout code
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18
      
      - name: Build
        run: go build -v ./...
    
      - name: Build Docker image
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ github.event.repository.name }}:latest, ${{ github.repository }}:latest

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
